#### general settings
name: DemosaicFormer_FineTuning
use_tb_logger: True
model: sr
distortion: sr
scale: 1
save_img: False
gpu_ids: [0, 1, 2, 3, 4, 5]


#### network structures
network_G:
  which_model_G: DemosaicFormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: BiasFree
  dual_pixel_task: False
  scale: 1

#### datasets
datasets:
  train:
    name: EvInt
    mode: LQGT
    use_augdata: False
    use_colorjitter: False

    dataroot_GT: /root/autodl-tmp/MIPI_dataset/train_copy/new_gt_1024
    dataroot_Frame: /root/autodl-tmp/MIPI_dataset/train_copy/new_qS_1024

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 12

    GT_size: 192
    use_flip: true
    use_rot: true
    color: RGB
    scale: 1
  val:
    name: EvInt_valid
    mode: LQGT
    dataroot_GT: /root/autodl-tmp/MIPI_dataset/test/gt_512
    dataroot_Frame: /root/autodl-tmp/MIPI_dataset/test/quadSamples_512
    scale: 1
  
#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  root: /root/autodl-tmp/MIPI_res

#### training settings: learning rate scheme, loss
train:
  optim_type: Adam
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 20000
  warmup_iter: -1
  T_period: [20000, 250000, 250000, 250000]
  restarts: [20000, 250000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 1e4

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4